/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eyckwu_androidmp3_utils_LameMp3 */

#ifndef _Included_com_eyckwu_androidmp3_utils_LameMp3
#define _Included_com_eyckwu_androidmp3_utils_LameMp3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eyckwu_androidmp3_utils_LameMp3
 * Method:    init
 * Signature: (Ljava/lang/String;IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_eyckwu_androidmp3_utils_LameMp3_init
  (JNIEnv *, jobject, jstring, jint, jint, jint, jstring);

/*
 * Class:     com_eyckwu_androidmp3_utils_LameMp3
 * Method:    encode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_eyckwu_androidmp3_utils_LameMp3_encode
  (JNIEnv *, jobject);

/*
 * Class:     com_eyckwu_androidmp3_utils_LameMp3
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_eyckwu_androidmp3_utils_LameMp3_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
